In [1]:
from update_feature_function_given_threshold import extract_json_file
import pandas as pd 
import numpy as np



#################################################################
### 	input information
#################################################################

video_list = ['DL00006', 'DS00005', 'EJ00004', 'LS00003', 'MSC00011']
time_list = [[16 + 5/6, 21+5/6], [15.5,20.5],[11.6666,16.6666], [11,16], [11,16]]

# Dv = []
# Dv2 = []
Dm = []


for i in range(len(video_list)):
    video_name = video_list[i]
    SCIT_start = time_list[i][0]
    SCIT_end = time_list[i][1]
    
#     Xv, Xv2, Xm = extract_json_file(video_name, SCIT_start, SCIT_end,  60)# 0.3, 0.75, 5,
    Xm = extract_json_file(video_name, SCIT_start, SCIT_end,  30)

#     Xv = pd.DataFrame(Xv)
#     Xv.columns = ['num_movement_scit1','list_movement_time_s_scit1', 'list_start_time_s_scit1']
#     body_part = ["Nose",  "Neck"
#                 ,  "RShoulder",  "RElbow",  "RWrist",  "LShoulder",  \
#                 "LElbow",  "LWrist",  "MidHip",  "RHip", "RKnee", "RAnkle", "LHip", "LKnee", \
#                 "LAnkle", "REye", "LEye", "REar", "LEar", "LBigToe", "LSmallToe", "LHeel", \
#                 "RBigToe", "RSmallToe", "RHeel"]
#     Xv.insert(0,'body_part',body_part)
#     print(Xv)
#     Dv.append(Xv)
    
#     Xv2 = pd.DataFrame(Xv2)
#     Xv2.columns = ['num_movement_scit1','list_movement_time_s_scit1', 'list_start_time_s_scit1']
#     body_part = ["Nose",  "Neck"
#                 ,  "RShoulder",  "RElbow",  "RWrist",  "LShoulder",  \
#                 "LElbow",  "LWrist",  "MidHip",  "RHip", "RKnee", "RAnkle", "LHip", "LKnee", \
#                 "LAnkle", "REye", "LEye", "REar", "LEar", "LBigToe", "LSmallToe", "LHeel", \
#                 "RBigToe", "RSmallToe", "RHeel"]
#     Xv2.insert(0,'body_part',body_part)
#     print(Xv2)
#     Dv2.append(Xv2)

    Xm = pd.DataFrame(Xm)
    Xm.columns = ['num_movement_scit1','list_movement_time_s_scit1', 'list_start_time_s_scit1']
    body_part = ["Nose",  "Neck",  "RShoulder",  "RElbow",  "RWrist",  "LShoulder",  \
                "LElbow",  "LWrist",  "MidHip",  "RHip", "RKnee", "RAnkle", "LHip", "LKnee", \
                "LAnkle", "REye", "LEye", "REar", "LEar", "LBigToe", "LSmallToe", "LHeel", \
                "RBigToe", "RSmallToe", "RHeel"]
    Xm.insert(0,'body_part',body_part)
    Dm.append(Xm)

starting extract DL00006 JSON files...
DL00006Number of movement based on magnitude:
11
0
2
0
0
0
0
0
0
0
0
1
0
0
1
8
22
2
7
1
1

C:\Users\Bu Yanyun\Desktop\video-analysis-testing\update_feature_function_given_threshold.py:65: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  plt.figure(figsize=(60,10))

1
1
0
0
starting extract DS00005 JSON files...
DS00005Number of movement based on magnitude:
34
14
19
11
12
16
11
10
7
4
3
2
4
3
2
31
31
29
33
2
2
2
2
2
2
starting extract EJ00004 JSON files...
EJ00004Number of movement based on magnitude:
33
2
0
2
1
3
2
3
16
2
3
5
3
1
5
34
37
14
20
7
8
6
7
6
4
starting extract LS00003 JSON files...
LS00003Number of movement based on magnitude:
28
1
4
3
3
2
3
3
4
1
1
1
2
1
1
27
24
25
13
1
1
1
1
1
1
starting extract MSC00011 JSON files...
MSC00011Number of movement based on magnitude:
3
0
0
0
1
0
0
0
1
0
1
1
1
3
2
9
9
3
4
2
2
2
1
1
2

In [2]:
# Dv = pd.concat(Dv, keys = video_list)
# Dv['total_movement_time_s_scit1'] = Dv['list_movement_time_s_scit1'].apply(lambda x: np.sum(x))

# Dv2 = pd.concat(Dv2, keys = video_list)
# Dv2['total_movement_time_s_scit1'] = Dv2['list_movement_time_s_scit1'].apply(lambda x: np.sum(x))

Dm = pd.concat(Dm, keys = video_list)
Dm['total_movement_time_s_scit1'] = Dm['list_movement_time_s_scit1'].apply(lambda x: np.sum(x))

In [3]:
# Dv.to_csv('test_v.csv')
# Dv2.to_csv('test_v2.csv')
Dm.to_csv('test_m.csv')

In [11]:
Dm_test = Dm.copy()
# the trick
unnested_lst = []
for col in Dm_test.columns:
    unnested_lst.append(Dm_test[col].apply(pd.Series).stack())
result = pd.concat(unnested_lst, axis=1, keys=Dm_test.columns)

In [12]:
result

                body_part  num_movement_scit1  list_movement_time_s_scit1  \
DL00006  0  0        Nose                11.0                         3.0
            1         NaN                 NaN                        23.0
            2         NaN                 NaN                        36.0
            3         NaN                 NaN                        92.0
            4         NaN                 NaN                        33.0
            5         NaN                 NaN                        27.0
            6         NaN                 NaN                        32.0
            7         NaN                 NaN                        26.0
            8         NaN                 NaN                        15.0
            9         NaN                 NaN                        18.0
            10        NaN                 NaN                        38.0
         1  0        Neck                 0.0                         NaN
         2  0   RShoulder                 2.0                        23.0
            1         NaN                 NaN                        47.0
         3  0      RElbow                 0.0                         NaN
         4  0      RWrist                 0.0                         NaN
         5  0   LShoulder                 0.0                         NaN
         6  0      LElbow                 0.0                         NaN
         7  0      LWrist                 0.0                         NaN
         8  0      MidHip                 0.0                         NaN
         9  0        RHip                 0.0                         NaN
         10 0       RKnee                 0.0                         NaN
         11 0      RAnkle                 1.0                        19.0
         12 0        LHip                 0.0                         NaN
         13 0       LKnee                 0.0                         NaN
         14 0      LAnkle                 1.0                        32.0
         15 0        REye                 8.0                        25.0
            1         NaN                 NaN                        30.0
            2         NaN                 NaN                        34.0
            3         NaN                 NaN                       129.0
...                   ...                 ...                         ...
MSC00011 15 5         NaN                 NaN                        46.0
            6         NaN                 NaN                        23.0
            7         NaN                 NaN                        11.0
            8         NaN                 NaN                         2.0
         16 0        LEye                 9.0                        79.0
            1         NaN                 NaN                        38.0
            2         NaN                 NaN                         4.0
            3         NaN                 NaN                        23.0
            4         NaN                 NaN                        21.0
            5         NaN                 NaN                         4.0
            6         NaN                 NaN                        23.0
            7         NaN                 NaN                        57.0
            8         NaN                 NaN                         6.0
         17 0        REar                 3.0                        31.0
            1         NaN                 NaN                        46.0
            2         NaN                 NaN                         5.0
         18 0        LEar                 4.0                        20.0
            1         NaN                 NaN                        58.0
            2         NaN                 NaN                         3.0
            3         NaN                 NaN                        48.0
         19 0     LBigToe                 2.0                         9.0
            1         NaN                 NaN                       111.0
         20 0   LSmallToe                 2.0                        19.0
            1         NaN                 NaN                        77.0
         21 0       LHeel                 2.0                        25.0
            1         NaN                 NaN                        87.0
         22 0     RBigToe                 1.0                       106.0
         23 0   RSmallToe                 1.0                        47.0
         24 0       RHeel                 2.0                        20.0
            1         NaN                 NaN                        57.0

               list_start_time_s_scit1  total_movement_time_s_scit1
DL00006  0  0                    17:14                        343.0
            1                    17:20                          NaN
            2                    18:14                          NaN
            3                    18:17                          NaN
            4                    18:46                          NaN
            5                    19:57                          NaN
            6                    20:19                          NaN
            7                    20:44                          NaN
            8                    20:56                          NaN
            9                    20:59                          NaN
            10                   21:46                          NaN
         1  0                      NaN                          0.0
         2  0                    18:14                         70.0
            1                    18:17                          NaN
         3  0                      NaN                          0.0
         4  0                      NaN                          0.0
         5  0                      NaN                          0.0
         6  0                      NaN                          0.0
         7  0                      NaN                          0.0
         8  0                      NaN                          0.0
         9  0                      NaN                          0.0
         10 0                      NaN                          0.0
         11 0                    18:18                         19.0
         12 0                      NaN                          0.0
         13 0                      NaN                          0.0
         14 0                    18:16                         32.0
         15 0                    17:00                        390.0
            1                    17:13                          NaN
            2                    17:35                          NaN
            3                    18:14                          NaN
...                                ...                          ...
MSC00011 15 5                    12:18                          NaN
            6                    13:12                          NaN
            7                    15:23                          NaN
            8                    15:59                          NaN
         16 0                    11:06                        255.0
            1                    11:11                          NaN
            2                    11:37                          NaN
            3                    11:45                          NaN
            4                    11:48                          NaN
            5                    12:19                          NaN
            6                    12:28                          NaN
            7                    13:12                          NaN
            8                    15:59                          NaN
         17 0                    11:00                         82.0
            1                    11:05                          NaN
            2                    15:59                          NaN
         18 0                    11:00                        129.0
            1                    11:05                          NaN
            2                    11:08                          NaN
            3                    11:11                          NaN
         19 0                    11:00                        120.0
            1                    11:05                          NaN
         20 0                    11:00                         96.0
            1                    11:06                          NaN
         21 0                    11:00                        112.0
            1                    11:06                          NaN
         22 0                    11:06                        106.0
         23 0                    11:07                         47.0
         24 0                    11:00                         77.0
            1                    11:06                          NaN

[792 rows x 5 columns]

In [13]:
result.to_csv('test_m_print.csv')